apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-taurus
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/SuryaLeon/provider-taurus
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A taurus that can be used to create Crossplane providers.

spec:
  controller:
    image: DOCKER_REGISTRY/provider-taurus-controller:VERSION
